### ISSUE TITLE
TO-DO nächste Woche

### ISSUE THREAD

**Issue by Pexem** [Richard-Sieg-TH-Koln/statistik-1-team-2#2]
- [ ] Notebook erstellen, Datensatz reinladen
- [ ] Statistiken aus dem Tutorial anwenden
- [ ] Eigene Statistik zu Lyrik länge hinzufügen
